-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 20, 2024 at 06:37 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pasi`
--

-- --------------------------------------------------------

--
-- Table structure for table `training_calendar`
--

CREATE TABLE `training_calendar` (
  `code` int(7) NOT NULL,
  `training` varchar(225) NOT NULL,
  `image` varchar(100) NOT NULL,
  `initial` varchar(50) NOT NULL,
  `introduction` longtext NOT NULL,
  `target_audience` longtext NOT NULL,
  `duration` varchar(50) NOT NULL,
  `status` varchar(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `training_calendar`
--

INSERT INTO `training_calendar` (`code`, `training`, `image`, `initial`, `introduction`, `target_audience`, `duration`, `status`) VALUES
(1, 'Records Management Conference', 'RMC.png', 'RMC', 'Records management involves the electronic storage of organization documents, physical storage of paper documents, custodial retention of cash equivalents, archive management, and use of third parties. To ensure the safety of organizational information an effective system for record management and archiving is required.\nThe business processes of institutions are improved by the presence of a good record management system. At the end of this course participants ought to have gained the knowledge and skills of efficient and effective record management and archiving.', 'This course targets all Records Management Professionals, Information Scientists, Secretaries, and all Key Personnel responsible for records in their organizations. The course also targets all individuals who want to improve their record management\nsystems.', '5 Days', '1'),
(2, '​Implementation of Modern Records Management through SharePoint & Office 365\nConference', 'IMRMSO.png', 'IMRMSO', 'Managing information and records, which are now one of the most valuable assets of the\ncompany represents a challenge in the modern world of digitalization where the\ncompanies are becoming digital enterprises and the data managed must get the new\nnames of data lakes and even the data oceans.\nAs most of the companies use the Microsoft Office programs and therefore the logical\nsolution for the Document Management will be to continue with the use of SharePoint.\nThe people within the companies should be well prepared for the challenges that this is\nbringing.\nDelivering information management solutions on SharePoint can be challenging, as the\nMicrosoft product offers very large number of options. In this training course, delegates\nwill apprehend how to combine the information management knowledge and apply it to\nSharePoint in ways that make it easy to use today and adaptable to the needs of the future.\nThis training course is ideally suited for any company that needs to build information\nmanagement solutions on SharePoint or use the product family related to SharePoint.\nThis PASI training course will highlight the elements, principles and implementation\npaths for modern information management challenges which require adaptability of the\nsolutions to the realm of Big Data environment and changing spectres of regulations.', 'This conference targets all professionals involved in data analysis, presentation, and\ngraphic design, but will be especially beneficial for: Document Controllers, Secretaries,\nAdministrators, Project Managers, Communication Specialists, Marketing Managers and\nPublic Relations Specialists and Business Development Managers', '5 Days', '1'),
(3, 'Professional Skills for Administrators & Secretaries', 'PSAS.png', 'PSAS', 'This practical and highly popular PASI Professional Skills for Administrators & Secretaries training course enables new and developing office professionals to make a powerful and positive impact in the workplace. It focuses on the essential core competencies that you will need to project a confident and efficient persona. Underpinning this is an in-depth exploration of the behaviours and skills necessary to achieve and sustain excellence in\r\nyour office environment.\r\nThis engaging, fun, and interactive Professional Skills for Administrators & Secretaries\r\ntraining course will help you to become more organised, to plan and prioritise and to\r\nmake effective decisions. It will help you to plan and set meaningful objectives. It will give\r\nyou the tools to become an excellent communicator and to be that valuable employee who\r\ncan deal calmly and effectively with difficult situations and people. It will also help you to\r\ncreate a harmonious and pleasant working atmosphere by teaching you how to deal with\r\nthe pressure and stress of the modern office.', 'This conference is suitable for a wide range of professionals but targets, Administrators,\r\nSecretaries\r\nExecutive Assistants, Personal Assistants, Office Managers, Supervisors, Business\r\nSupport staff.', '5 Days', '1'),
(4, 'Advanced Budgeting and Cost Management', 'ABCM.png', 'ABCM', 'This advanced Budgeting & Cost Management Conference provides participants with key\r\ncost awareness and budgetary skills, which are essential for managing and controlling\r\nresources in times of increasing global competition where the budgets are inextricably\r\nlinked with both the achievement of strategic objectives as well as with evaluation of\r\nfuture plans and initiatives.\r\nBudgeting and cost analysis are crucial elements for the management of contemporary\r\norganizations. Nowadays, if companies want to stay competitive, they are urged to link\r\ntheir strategies with accurate systems of resource allocation and performance\r\nmeasurement.\r\nAlong this line, budgeting, as well as tracking, controlling & reducing cost represent\r\nessential activities to be performed and monitored by organizations as they implement\r\ntheir key processes, activities, and operations. In addressing these issues, this training\r\ncourse is relevant for those professionals & analysts facing the difficult challenge of\r\nimproving performance while reducing costs of those processes for which there are\r\naccountable', 'This conference is suitable for a wide range of professionals but will greatly benefit:\r\nBudget Staaf, Financial Controllers, Treasury Accountants, Management Accountants,\r\nFinancial Professionals, Professional R&D, Sales / Marketing Professional, General\r\nAccounting Professional, Business Unit Professionals and Procurement Professionals', '5 Days', '1'),
(5, 'Treasury and Risk Management', 'TRM.png', 'TRM', 'The Treasury & Risk Management function is essential to the success and sustainability\r\nof all leading corporate organisations. Never has this been truer, given the ever-increasing\r\npace of change in regulation, compliance, technology, and financial risk.\r\nTreasury Management ensures sufficient liquidity to meet obligations, whilst managing\r\npayments, receipts, and financial risks such as Credit Risk, Oil Price, Exchange Rate, and\r\nInterest Rate Risk effectively. In addition, effective Treasury & Risk Management will\r\nenable companies to make informed and better strategic decisions, providing the analysis,\r\nfinance, and risk assessment.\r\nThe aim of this conference, therefore, is to provide participants with the knowledge and\r\nskills to make an effective contribution to the Treasury & Risk Management function', 'Given the importance of the Treasury & Risk Management, this Conference will greatly\r\nbenefit:\r\nTreasury & Risk Management Professionals, Financial Decision-makers, and managers\r\nand those with financial responsibilities', '5 Days', '1'),
(6, 'Auditing Corporate Governance; Assessing your business direction', 'ACG.png', 'ACG', 'Corporate Governance is now one of the hottest topics in the business world. It is both a\r\nregulatory requirement and a business enabler.\r\nBut do you know whether your Corporate Governance activities are extracting\r\nmaximum value? If not, this is probably because your Internal Audit team have not\r\nassessed this key topic.\r\nThis audit approach is crucial as the Board and the Audit Committee need\r\ncomprehensive assurance about this strategic business process.\r\nThis Auditing Corporate Governance training course will provide all the tools and\r\ntechniques essential to audit the complex and wide-ranging field of Corporate\r\nGovernance. It will help you ensure that you are applying the very best practices and\r\nmeet all regulatory requirements', 'This conference is suitable for a wide range of professions but will greatly benefit; Board\r\nManagers, Joint Venture Coordinators, Lead Auditors, Senior Auditors, Audit Managers,\r\nCorporate Governance Managers and Managers needing a broader understanding of how\r\nto review Governance maturity', '5 Days', '1'),
(7, 'Advanced Office Management and Effective Administrative Skills', 'AOMEAS.png', 'AOMEAS', 'This highly interactive Advanced Office Management & Effective Administration Skills\r\ntraining course will help you to develop and refine the skills needed to excel as an Office\r\nManager, Administrator or Executive Secretary. It will explore in depth the interpersonal\r\nand behavioural skills necessary to ensure you are well prepared for the challenges of\r\nworking with a variety of management styles. On this Office Administration training\r\ncourse, you will also learn how to stay in control whilst dealing with conflicting priorities.\r\nBecoming more effective as an Office manager will make your job easier and make you\r\nmore valuable in the eyes of your managers and the company stakeholders. Office\r\nManagers need to be expert multi-taskers – even if you’re doing more than four things at\r\nonce, that’s probably still not enough! You need to be indispensable – to know exactly who\r\nto call to fix that pesky problem your boss has. And to be truly indispensable you need to\r\nbe organised, be an excellent communicator, and be able to deal with whatever\r\nchallenging situation your working life presents you with. This Advanced Office\r\nManagement & Effective Administration Skills training course will help you to do that', 'This training course is suitable to a wide range of professionals but will especially benefit:\r\nOffice Managers, Team Leaders, Administrators, Supervisors, Secretaries, Support Staff\r\nand Personal Assistants', '5 Days', '1'),
(8, 'Strategic Talent Management', 'STM.png', 'STM', 'Identifying, developing, and retaining your talent has never been more important for the\r\nindustry with the ever-changing economic market. An organisation’s best and most asset\r\nis undoubtedly the people; as it’s the people who operate the systems, the equipment and\r\nwho can really make the difference between growth or failure. Losing or not being able to\r\nrecruit the best talent can have a disastrous impact on an organization’s growth and\r\nsustainability. This highly interactive Strategic Talent Management training course will\r\nteach you the key talent management processes, systems, and procedures to apply these\r\nin the multi-complex industries.\r\nOn this training course, you will gain insight into innovative talent identification methods,\r\ndevelop targeted grading structures, review, and develop competency / behavioural\r\nframeworks as well as how to grade and assess your talent/high potentials with the\r\neffective use of psychometric tools and other assessment methods. In addition, you will\r\ndefine critical development options ensuring the correct development for talent in the\r\norganisation. You will also learn how to create sustained growth through active\r\nsuccession planning and strategy to ensure positive career paths and development for\r\ntalent and high potential employees', 'This training course on Strategic Talent Management will greatly benefit individuals,\r\naligned to the identification, development and retention of talent and high potential\r\npeople in the business, including: Human Resource Managers, HR / L&D / Talent\r\nProfessionals, Training Managers, and Recruitment Officers and Managers', '5 Days', '1'),
(9, 'Advanced Electronic Document Management Systems', 'AEDMS.png', 'AEDMS', 'A document management system is a computer system used to track and store electronic\r\ndocuments. It is usually also capable of keeping track of the different versions modified\r\nby different users. The term has some overlap with the concepts of content management\r\nsystems. It is often viewed as a component of enterprise content management systems\r\nand related to digital asset management, document imaging, workflow systems and\r\nrecords management systems. This course shows you how to deal with papers in an\r\nelectronic way to get rid of the papers hard copy which takes a lot of space and time', 'This training course is suitable to a wide range of professionals but will especially benefit;\r\nCompliance Officers/Managers, Information Security Managers, Archivists, Records\r\nManagers, Information Managers, Operations Managers, Knowledge Managers,\r\nAdministrators, Librarians and Secretaries', '5 Days', '1'),
(10, 'Electronic Records and Archives Management', 'ERAM.png', 'ERAM', 'Electronic Records & Archives Management is the process of creating, managing,\r\ntracking, and storing electronic records and archives within an organization’s workflow.\r\nIt involves the digitalization of information, standardizing document workflow systems,\r\nand records management systems with the aim of eliminating hard copy papers which\r\nconsumes the organizations space and time.\r\nIn modern businesses and organizations, a well-designed and properly implemented\r\nelectronic document management system supports in eliminating manual processes to\r\ngaining quick access to relevant information and documents directly on electronic\r\ndevices, maintaining the relationship between documents and physical spaces,\r\ncontrolling document user update versions while maintaining the quality and accuracy of\r\nthe organizations documents.\r\nThis course is intended to equip participants with understanding and skills on organizing,\r\ndistributing, and integrating business/organizations documents to simplify the\r\nprocesses, allowing your team to instant access to different types of documents within\r\nand outside the office', 'This training course is suitable to a wide range of professionals but will especially benefit;\r\nCompliance Officers/Managers, Information Security Managers, Archivists, Records\r\nManagers, Information Managers, Operations Managers, Knowledge Managers,\r\nAdministrators, Librarians and Secretaries', '5 Days', '1'),
(11, 'Electronic Document Management Systems', 'EDMS.png', 'EDMS', 'Information, no matter how it is initially produced or collected, is becoming an\r\nincreasingly asset for organizations today, while simultaneously the requirements to\r\narchive information are becoming more complex. Finding an efficient approach to\r\narchiving information across all material aspects of its lifecycle – from its creation to its\r\ndefined destruction – is a challenge. At the same time, the need to establish such an\r\nefficient approach is essential, with benefits in cost-cutting and organizational\r\nperformance being paramount. This training is design to show participants how to deal\r\nwith papers in an electronic way to get rid of the papers hard copy which takes a lot of\r\nspace and time', 'This training course is suitable to a wide range of professionals but will especially benefit;\r\nCompliance Officers/Managers, Information Security Managers, Archivists, Records\r\nManagers, Information Managers, Operations Managers, Knowledge Managers,\r\nAdministrators, Librarians and Secretaries', '5 Days', '1'),
(12, 'International Financial Reporting Standards', 'IFRS.png', 'IFRS', 'The International Financial reporting standards course will help build the knowledge you\r\nneed in IFRS for success in today’s global business world. The course will cover most of\r\nthe international accounting standards and international financial reporting standards. It\r\nwill help participants gain an understanding of global accounting standards and their\r\npractical use in the preparation of financial statements.\r\nDeveloped with input from subject matter experts from across the region, this course is\r\ndesigned to provide accounting and finance professionals with the knowledge and\r\npractical skills needed to use IFRS and stay up to date with the newest standards and\r\nchanges', 'Professionals in the fields of finance and accounting as well as professionals seeking to\r\nenhance their international accounting knowledge from companies implementing IFRS\r\nas the standard of reporting', '5 Days', '1');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `training_calendar`
--
ALTER TABLE `training_calendar`
  ADD PRIMARY KEY (`code`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `training_calendar`
--
ALTER TABLE `training_calendar`
  MODIFY `code` int(7) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
